### ISSUE TITLE
sample token.properties

### ISSUE THREAD

**Issue by FabianTerhorst** [Ale46/jgroove#1]
Hello,

can you upload a token.properties file with the current keys?

**Comment by Ale46** [comment]
Hi,
the current token.properties, also if it's 2 years old, should have the latest keys. I also just tested some functions and all work correctly.

**Comment by FabianTerhorst** [comment]
but i get {"header":{"session":""},"fault":{"code":16,"message":"invalid session"}} on popular songs

**Comment by Ale46** [comment]
I just runned this code
```java
import jgroove.JGroovex;

import java.io.IOException;
import java.util.HashMap;

public class Main {

    public static void main(String[] args) throws IOException {
        HashMap<String, String>[] songs = JGroovex.getPopularSongs("monthly").result.Songs;
        for (HashMap<String, String> song : songs)
            System.out.println(song.get("ArtistName") + " - " + song.get("Name"));
    }
}
```
that returns:
```
{"header":{"session":"6b9175ea9f3baa0403bfcabc3d6fcb--","serviceVersion":"20100903","prefetchEnabled":true},"result":"03ad8151158f7b8525ed95a2629860ad85bb3a--"}
MAROON5 - Sugar
Sia - Elastic Heart
Calvin Harris - Outside (feat. Ellie Goulding)
...
...
```
Check that you have the last commited version and you haven't blacklisted from grooveshark.

**Comment by FabianTerhorst** [comment]
when i do 

try {

            Tasks.executeInBackground(this, new BackgroundWork<String>() {
                @Override
                public String doInBackground() throws Exception {

                    HashMap<String, String>[] popularSongs = JGroovex.getPopularSongs("daily").result.Songs;
                    for (int i = 0; i < popularSongs.length; i++) {
                        Log.d("song " + i, popularSongs[i].toString());
              
                        String songId = popularSongs[i].get("SongID");
                        JsonGetSong jsonGetSong = JGroovex.getSongURL(songId);
                        Log.d("jsongetsong",jsonGetSong.toString());

                    }

                    return null;
                }
            }, new Completion<String>() {
                @Override
                public void onSuccess(Context context, String result) {

                }

                @Override
                public void onError(Context context, Exception e) {

                }
            });

        }catch(Exception io){
            io.printStackTrace();
        }

i get a list of the popular songs but i get a invalid session error on getSongURL()

**Comment by Ale46** [comment]
Try to stream a song from grooveshark.com, maybe you get banned, because for me also this works fine
```
{"header":{"session":"4a3742c1a4d6431c618ebbdfcca6152c","serviceVersion":"20100903","prefetchEnabled":true},"result":"f97dc8ad323df5e77566c1f7320b64e866ec5b74"}
MAROON5 - Sugar
{"header":{"session":"4a3742c1a4d6431c618ebbdfcca61---","serviceVersion":"20100903","prefetchEnabled":true},"result":{"FileID":"66719446","uSecs":"235000000","FileToken":"7hwNAg","ts":1428342734,"isMobile":false,"SongID":41999592,"streamKey":"857d43b6d4151e37adddbddabe7f5c20b08fae76_5522ced6_280dce8_3fa0ed6_186337---_1_0","Expires":1428344534,"streamServerID":1024,"ip":"stream---a.grooveshark.com"}}
```

**Comment by FabianTerhorst** [comment]
in my country grooveshark is banned

**Comment by Ale46** [comment]
So this is the problem. You can try to run your code behind a proxy to bypass the regional restriction.
```
java -Dhttp.proxyHost=proxyserver.com  -Dhttp.proxyPort=proxy_port YOUR_CLASS
```
But first check your country's laws before do something.

Have fun

**Comment by FabianTerhorst** [comment]
on my cpp class i have writen few years ago. everything works. I try now to find differences.
